apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: postgres
data:
  POSTGRES_URL: jdbc:postgresql://localhost:5432/cookingapp
#  POSTGRES_DB: cookingapp
#  POSTGRES_USER: cookingapp
#  POSTGRES_PASSWORD: supermegapassowrd
