apiVersion: apps/v1
kind: Deployment
metadata:
  name: receipts
  namespace: cookingapp
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: receipts
    spec:
      containers:
      - name: receipts
        image: adrianstanete/receipts-image:latest
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: receipts-config
        env:
        - name: ASPNETCORE_URLS
          value: http://*:80
        - name: DB_HOST
          value: postgres
        - name: DB_PORT
          value: "5432"
        - name: USER_NAME #from the DB
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: USER_NAME
        - name: USER_PASSWORD #from the DB
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: USER_PASSWORD


  selector:
    matchLabels:
      app: receipts
---
apiVersion: v1
kind: Service
metadata:
  name: receipts
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: receipts