apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
  name: cookingapp-ingress
  namespace: cookingapp
spec:
  tls:
  - hosts:
    - kubernetes.default.svc.cluster.local
  rules:
  - host: cookingapp.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: receipts-chart
            port:
              number: 80
